SELECT 'PREPAGA' AS tabla, COUNT(*) AS cantidad_registros FROM PREPAGA
UNION ALL
SELECT 'PACIENTE', COUNT(*) FROM PACIENTE
UNION ALL
SELECT 'TELEFONO_PACIENTE', COUNT(*) FROM TELEFONO_PACIENTE
UNION ALL
SELECT 'TORRE', COUNT(*) FROM TORRE
UNION ALL
SELECT 'HABITACION', COUNT(*) FROM HABITACION
UNION ALL
SELECT 'CONSULTORIO', COUNT(*) FROM CONSULTORIO
UNION ALL
SELECT 'SERVICIO', COUNT(*) FROM SERVICIO
UNION ALL
SELECT 'ESPECIALIDAD', COUNT(*) FROM ESPECIALIDAD
UNION ALL
SELECT 'MEDICO', COUNT(*) FROM MEDICO
UNION ALL
SELECT 'TELEFONO_MEDICO', COUNT(*) FROM TELEFONO_MEDICO
UNION ALL
SELECT 'HISTORIA_CLINICA', COUNT(*) FROM HISTORIA_CLINICA
UNION ALL
SELECT 'OCUPA', COUNT(*) FROM OCUPA
UNION ALL
SELECT 'BRINDA', COUNT(*) FROM BRINDA;